name: plug2go
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+18

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  auto_size_text: "^3.0.0"
  cloud_firestore: 5.2.1
  connectivity_plus: ^6.0.5
  cupertino_icons: "^1.0.6"
  firebase_auth: 5.1.4
  firebase_core: 3.3.0
  firebase_messaging: 15.0.4
  flutter:
    sdk: flutter
  # flutter_kronos: ^0.1.0+1
  flutter_kronos_plus: ^1.0.0+1
  flutter_lazy_indexed_stack: "^0.0.6"
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: "^5.9.3"
  flutter_stripe: ^11.2.0
  flutter_svg: "^2.0.10+1"
  flutter_timezone: ^3.0.1
  form_field_validator: "^1.1.0"
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: 12.0.0
  google_maps_flutter: "^2.9.0"
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  json_annotation: ^4.9.0
  logger: "^2.4.0"
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  pinput: "^5.0.0"
  pkg_dio:
    path: pkg_dio
  provider: "^6.1.2"
  socket_io_client: ^3.0.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

dependency_overrides:
  web: ^0.5.1 # resolves the conflict

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-Light.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf

flutter_gen:
  {
    line_length: 120,
    integrations: { flutter_svg: true, lottie: true },
    fonts: { enabled: true, outputs: { class_name: FontFamily } },
  }
