name: pkg_dio
description: Dio helper package
version: 0.0.1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1
  dio: ^5.7.0
  #  dio_http2_adapter: ^2.5.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  logger: ^2.4.0
  native_dio_adapter: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  very_good_analysis: ^6.0.0

dependency_overrides:
  analyzer: ">=6.5.0 <7.0.0"
  meta: ^1.15.0
